config/routes.rb
KITBox::Application.routes.draw do

  mount API => '/api'

  resources :dashboard, only: :index
  resources :documents, only: :new
  resources :search, only: :index
  resources :users, only: [:new]
  
  
  resources :timetable, only: :index do
    collection do
      get 'regenerate'
      get 'exam'
    end
  end
  match '/timetable/:timetable_id.ics', to: 'timetable#ical', :as => :timetable_ical


  resources :events, only: [:show] do
    member do
      get 'subscribe'
      get 'unsubscribe'
      get 'dates'
    end
    resources :dates, controller: "event_dates", only: [:new, :create]
  end
  

  resources :map, only: [:index, :show] do
    collection do
      get 'search'
      get 'list'
    end
  end
  

  resources :vvz, only: [:index, :show, :preload] do
    member do
      get "events/:event_id" => "vvz#events", :as => :event
      get "preload", format: "js"
    end
  end


  # skips login proccess
  if %w( development test cucumber ).include?(Rails.env.to_s)
    match "/backdoor" => "sessions#backdoor", :as => :backdoor
  end


  post "/signin" => "sessions#create", :as => :signin
  match "/signout" => "sessions#destroy", :as => :signout
  match "/signup" => "users#new", :as => :signup


  get '/robots.txt' => 'welcomes#robots'


  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  root :to => 'dashboard#index', :constraints => RoleConstraint.new(:user)
  root :to => redirect("/vvz")

  # See how all your routes lay out with "rake routes"
end

app/models/event.rb
class Event < ActiveRecord::Base
  include PgSearch
  has_and_belongs_to_many :vvzs#, uniq: true
  has_and_belongs_to_many :users
  has_many :event_dates, :dependent => :destroy #, :as => :dates
  has_many :activities, class_name: "EventActivity"
  
  include PgSearch
  multisearchable :against => [:name, :nr, :lecturer, :description]

  pg_search_scope :vvz_search,
    :against => :name,
    :using => {
      :tsearch => {:prefix => true},
      :trigram => {:prefix => true}
    }

  # scope :today, lambda { 
  #   joins(:event_dates).where("DATE(start_time) = DATE(?)", Time.now)
  # }

  # scope :not_ended, lambda { 
  #   where('end_time > ?', Time.now)
  # }

  # scope :tomorrow, lambda { 
  #   joins(:event_dates).where("DATE(start_time) = DATE(?)", Time.now + 1.day)
  # }

  def track_activity(action, data={})
    activity = activities.new action: action
    activity[:data] = data
    activity.save
    activity
  end

  def subscribe(user)
    user.events << self
  end

  def unsubscribe(user)
    user.events.delete self
  end

  def subscribed?(user)
    user.events.include? self
  end

  JSON_PREFIX = "*"

  def name=(name)
    write_attribute(:name, name)
    # ensure that original_name is set
    write_attribute(:original_name, name) if original_name.nil?
  end

  def to_preload
    children = children!.map { |n| n.preload_id }
    [preload_id, name, children]
  end 

  def preload_id
    JSON_PREFIX + id.to_s
  end

  def children!
    events
  end

  def dates; event_dates end
    
  def week
    EventDate.week(id)
  end

  def group_by_day
    groups = dates.group_by {|d| d["time"] + Date.parse(d["date"]).wday.to_s + d["room"] }
    groups.values.map(&:first)
  end
  
  def self.to_ical(events)
    RiCal.Calendar do |cal|
      events.each do |event|
        event.dates.each do |date|
          start_time, end_time = date["time"].split("-")
          date_s = date["date"]
          
          cal.event do |e|
            e.summary     = event.name
            #event.description = "First US Manned Spaceflight\n(NASA Code: Mercury 13/Friendship 7)"
            e.dtstart     = Time.parse(start_time + " " + date_s).getutc
            e.dtend       = Time.parse(end_time + " " + date_s).getutc
            e.location    = date["room"]
            e.url         = event.url
          end
        end
      end
    end
  end

  def as_json(user=nil)
    keys = [:name, :nr, :url, :lecturer].map(&:to_s)
    data = self.attributes.slice(*keys)
    data[:type] = simple_type.rstrip
    data[:description] = j_description
    if user
      data[:authenticated] = true
      data[:subscribed] = subscribed?(user)
    end
    data
  end
  
  # only rails should change these attributes
  SAFE_ATTRIBUTES = [:id, :created_at, :updated_at]

  def same_as?(other)
    self.save_attributes == other.save_attributes
  end

  def save_attributes
    ignored_keys = SAFE_ATTRIBUTES.map(&:to_s)
    self.attributes.except(*ignored_keys) 
  end

  def find_or_create
    Event.where(self.save_attributes).first || self.save && self
  end

  def simple_type
    self._type[/^([^(, ]*)/].to_s
  end

  def j_description
    if data = read_attribute(:description)
      hash = JSON.parse data
      text = hash.reduce("") do |s, item|
        s << "<section class=\"desc\">"
        s << "<h4>%s</h4>" % item[0]
        s << item[1]
        s << "</section>"
      end
      text.html_safe
    end
  rescue JSON::ParserError => e
    logger.warn e.message
    read_attribute(:description).html_safe
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
    
  def show
    @event = Event.find(params[:id])
    respond_to do |format|
      format.html { 
        authorize
        @event = Event.find(params[:id])
      }
      format.json do 
        data = @event.as_json(current_user)
        data[:authenticated] = !!current_user
        render json: data 
      end
    end
  end

  def dates
    @event = Event.find(params[:id])
  end
  
  def subscribe
    event = Event.find(params[:id])
    event.subscribe current_user
    respond_to do |format|
      format.html { redirect_to :back, notice: 'Erfolgreich angemeldet' }
      format.json { render json: { message: "Erfolgreich angemeldet" }  }
    end
  end
  
  def unsubscribe
    event = Event.find(params[:id])
    current_user.events.delete event
    respond_to do |format|
      format.html { redirect_to :back, notice: "Erfolgreich abgemeldet" }
      format.json { render json: { message: "Erfolgreich abgemeldet" }  }
    end
  end

  
end

app/helpers/events_helper.rb
# encoding: UTF-8
module EventsHelper
  
  def url_to_ical(url)
    url = url.split("://").last
    "webcal://#{url}.ics"
  end
  
  def event_pos(date, time)
    start_time, end_time = time.split("-")
    
    day = Date.parse(date).wday
    day = 0 if day >= 7
    
    sh, sm =  start_time.split(":");
    sh = sh.to_i - 7 #start at 7:00
    sm = sm.to_i / 15 #viertelstundentakt
    start = sh*4 + sm
    
    eh, em =  end_time.split(":");
    eh = eh.to_i - 7
    em = em.to_i / 15
    duration = (eh-sh)*4 + (em-sm)
    #binding.pry
    "d#{day} s#{start} l#{duration}"
  end
  
  def to_german_day(date)
    days = %w(Sonntag Montag Dienstag Mittwoch Donnerstag Freitag)
    i = Date.parse(date).wday
    days[i] + "s"
  end

  def pretty_event_date(date)
    days = %w(Sonntag Montag Dienstag Mittwoch Donnerstag Freitag)
    s = date.start_time
    e = date.end_time
    if s.to_date == s.to_date
      day = days[s.wday]
      "#{day}, #{s.strftime("%d.%m.%Y <span class=\"seperator\" /> %H:%M")} - #{e.strftime("%H:%M")}".html_safe
    else
      "#{s.strftime("%d.%m.%Y %H:%M")} - #{e.strftime("%d.%m.%Y %H:%M")}"
    end
  end

  def next_date(event, date)
    time = date.start_time
    text = ""
    text << "<em>" << date_to_human(time) << " "
    text << time.strftime("%H:%M Uhr") << "</em> "
    text << "in <em>" << @next.room << "</em>"
    text.html_safe
  end

  def date_to_human(date)
    if date < 7.days.from_now
      german_day(date)
    else
      date.strftime("%d.%m.")
    end
  end

  def german_day(date)
    days = %w(Montag Dienstag Mittwoch Donnerstag Freitag Samstag Sonntag)
    days[date.wday]
  end

end

app/views/events/_form.html.erb
<%= simple_form_for @event do |f| %>
  <%= f.input :nr %>
	<%= f.input :name %>
	<%= f.input :lecturer %>
  <%= f.input :type, :collection=> Event::TYPES %>
  <%= f.input :term, :input_html => { :value => "ws11" }, :disabled=>true %>
	<%= f.input :faculty %>
	<%= f.input :link %>
	<div class="actions">
  	<%= f.button :submit, :class=> "btn primary" %>
		<button type="reset" class="btn">​Cancel​</button>
	</div>
<% end %>

app/views/events/_header.html.slim
header
  ul.pull-right.inline
    li 
      - if @event.subscribed?(current_user)
        a.btn.subscribe.btn-small href=unsubscribe_event_path(@event)
          | abmelden
      - else
        a.btn.unsubscribe.btn-small href=subscribe_event_path(@event)
          | anmelden

  h1= @event.name
  .lecturer
    = @event.lecturer
 
  .clearfix


  nav
    ul.nav.nav-tabs
      li class=(request.path == event_path(@event) && "active")
        a href=event_path(@event) Beschreibung
      li class=(request.path == dates_event_path(@event) && "active")
        a href=dates_event_path(@event) Termine
      li
        a href=@event.url target="_blank"
          i.icon-external-link
          |  offiziellen Seite

app/views/events/dates.html.slim
.container
  .content#event_page
    = render partial: "header"

    /a#add-exam-date.btn href=new_event_date_path(@event, type: :exam) 
      i.icon-plus
      |  Klausurtermin

    - dates = @event.dates.order("start_time")
    - if dates.count > 0
      .dates
        - future_dates, past_dates = dates.partition {|date| !date.end_time.past? }
        h3 Termine
        ul.unstyled.future_dates
          - future_dates.each do |date|
            li
              .date= pretty_event_date(date)
              span.seperator
              .room
                | Raum: 
                = date.room
        - if past_dates.count > 0
          a.collapse-btn href="javascript:;" rel="collapse" data-target=".past_dates" Zeige verangene Termine
          ul.unstyled.past_dates.hide
            - past_dates.each do |date|
              li
                .date= pretty_event_date(date)
                span.seperator
                .room
                  | Raum: 
                  = date.room
      

app/views/events/edit.html.erb
<div class="page-header">
	<h1>Editing event</h1>
</div>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.slim
h1 Veranstaltungen

br 
br


- @events.each do |e|
 p 
  h3
    = link_to e.name, event_path(e)
  div.termine
    - if e.group_by_day.empty?
      | keine Termine verfügbar
    - e.group_by_day.each do |d|
      div.termin
        = to_german_day d["date"]
        = " " + d["time"]
        .room 
          | Ort: 
          = d["room"]



/
  - wochentage = %w(Montag Dienstag Mittwoch Donnerstag Freitag Samstag Sonntag)
  #stundenplan
    table.table
      thead 
        tr
          th 
          - wochentage.each do |day|
            th= day
      tbody
        - (7..20).each do |time|
          tr
            td= time
            - 7.times do
              td 
          tr
            - 8.times do
              td
    / .event.d3.s7.l4 hallo
    - @events.each do |event|
      - event.group_by_day.each do |d|
        - classes = event_pos(d["date"], d["time"])
        .event class=classes
          b= event.name
          br
          small= "#{d["time"]}, #{d["room"]}"
  br
  br

  table#minitable.table
    thead
      tr
        th.first
        - %w(M D M D F S S).each do |day|
          th= day
    tbody
      - (7..20).each do |h|
        tr.first
          td rowspan="4" = h
          - 7.times do
            td
        - 3.times do
          tr
            - 7.times do
              td
            
            
  table#minitable2.table
    thead
      tr
        th
        - (7..20).each do |h|
          th= h
    tbody
      - %w(M D M D F S S).each do |day|
        tr
          td= day
          - (7..20).each do |h|
            td
              table
                tr
                  td
                  td
                  td
                  td


      
      

br
br
a.btn.btn-primary href=url_to_ical(events_url) target="_blank"
  i.icon-calendar.icon-white
  |  Zu deinem Kalender hinzufügen
br
br
| Oder importiere die iCalendar-Datei in deinen Kalender:  
a.btn.btn-mini href="#{events_url}.ics" 
  i.icon-download  
  |  events.ics

app/views/events/new.html.erb
<div class="page-header">
	<h1>New event</h1>
</div>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.slim
- page_title @event.name
.container
  .content#event_page
    = render partial: "header"
    
    #event-description-tab
      = @event.j_description