config/routes.rb
KITBox::Application.routes.draw do

  mount API => '/api'

  resources :dashboard, only: :index
  resources :documents, only: :new
  resources :search, only: :index
  resources :users, only: [:new]
  
  
  resources :timetable, only: :index do
    collection do
      get 'regenerate'
      get 'exam'
    end
  end
  match '/timetable/:timetable_id.ics', to: 'timetable#ical', :as => :timetable_ical


  resources :events, only: [:show] do
    member do
      get 'subscribe'
      get 'unsubscribe'
      get 'dates'
    end
    resources :dates, controller: "event_dates", only: [:new, :create]
  end
  

  resources :map, only: [:index, :show] do
    collection do
      get 'search'
      get 'list'
    end
  end
  

  resources :vvz, only: [:index, :show, :preload] do
    member do
      get "events/:event_id" => "vvz#events", :as => :event
      get "preload", format: "js"
    end
  end


  # skips login proccess
  if %w( development test cucumber ).include?(Rails.env.to_s)
    match "/backdoor" => "sessions#backdoor", :as => :backdoor
  end


  post "/signin" => "sessions#create", :as => :signin
  match "/signout" => "sessions#destroy", :as => :signout
  match "/signup" => "users#new", :as => :signup


  get '/robots.txt' => 'welcomes#robots'


  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  root :to => 'dashboard#index', :constraints => RoleConstraint.new(:user)
  root :to => redirect("/vvz")

  # See how all your routes lay out with "rake routes"
end

app/models/event_date.rb
class EventDate < ActiveRecord::Base
  belongs_to :event
  self.inheritance_column = nil
  
  validates :start_time, presence: true


  #EventDate.where(event_id: events)

  # scope :upcomming, lambda { 
  #   not_ended.where("DATE(start_time) = DATE(?) OR DATE(start_time) = DATE(?)", Time.now, Time.now + 1.day)
  # }

  scope :today, lambda { day(Time.now) }

  scope :not_ended, lambda { 
    where('end_time > ?', Time.now)
  }

  scope :tomorrow, lambda { day(Time.now + 1.day) }

  scope :day, lambda { |day|
    where("DATE(start_time) = DATE(?)", day)
  }

  scope :after_now, lambda {
    where('end_time < ?', Time.now).order(:end_time)
  }

  scope :by_user, lambda { |user|
    joins(:event => :users).where("users.id" => User.first)
  }

  # Returns the day of the date as an Integer
  # monday = 0, tuesday = 1, ..., sunday = 6
  def day
    index = start_time.wday # sunday = 0, monday = 1, ...
    index == 0 ? 6 : index - 1
  end

  def today?
    start_time.today?
  end

  def title
    t = ""
    t += event.name
    t += " (Klausur)" if type == "exam"
    t
  end

  def start_time
    correct_time read_attribute(:start_time)
  end

  def end_time
    correct_time read_attribute(:end_time)
  end

  private

  def correct_time(time)
    time.in_time_zone("CET") - 1.hour
  end

end

app/controllers/event_dates_controller.rb
class EventDatesController < ApplicationController

  before_filter :authorize
  
  # def index
  #   @event_dates = EventDate.all

  #   respond_to do |format|
  #     format.html # index.html.erb
  #     format.json { render json: @event_dates }
  #   end
  # end

  # def show
  #   @event_date = EventDate.find(params[:id])

  #   respond_to do |format|
  #     format.html # show.html.erb
  #     format.json { render json: @event_date }
  #   end
  # end

  def new
    @event = Event.find params[:event_id]
    @event_date = @event.dates.build type: params[:type]

    if params[:type] == "exam"
      render :new_exam
    else
      raise "No Type specified!"
    end
  end

  def create
    @event = Event.find params[:event_id]
    params[:event_date]["end_time(3i)"] = params[:event_date]["start_time(3i)"]
    params[:event_date]["end_time(2i)"] = params[:event_date]["start_time(2i)"]
    params[:event_date]["end_time(1i)"] = params[:event_date]["start_time(1i)"]
    @event_date = @event.dates.build params[:event_date]

    if @event_date.save
      redirect_to dates_event_path(@event), notice: 'Termin erfolgreich gespeichert.'
    else
      render action: "new"
    end
  end

  # def update
  #   @event_date = EventDate.find(params[:id])

  #   respond_to do |format|
  #     if @event_date.update_attributes(params[:event_date])
  #       format.html { redirect_to @event_date, notice: 'Event date was successfully updated.' }
  #       format.json { head :ok }
  #     else
  #       format.html { render action: "edit" }
  #       format.json { render json: @event_date.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # def destroy
  #   @event_date = EventDate.find(params[:id])
  #   @event_date.destroy

  #   respond_to do |format|
  #     format.html { redirect_to event_dates_url }
  #     format.json { head :ok }
  #   end
  # end
end

app/helpers/event_dates_helper.rb
module EventDatesHelper
end

app/views/event_dates/_form.html.slim
= form_for @event_date do |f|
  -if @event_date.errors.any?
    #error_explanation
      h2 = "#{pluralize(@event_date.errors.count, "error")} prohibited this event_date from being saved:"
      ul
        - @event_date.errors.full_messages.each do |msg|
          li= msg
  
  .field
    = f.label :date, "Datum"
    = text_field EventDate, :date
  .field
    = f.label :start_time, "Beginn"
    = f.text_field :start_time, :size => 4
  .field
    = f.label :end_time
    = f.datetime_select :end_time
  .field
    = f.label :room
    = f.text_field :room
  .actions
    = f.submit 'Save'

app/views/event_dates/edit.html.slim
h1 Editing event_date

== render 'form'

= link_to 'Show', @event_date
'|
= link_to 'Back', event_dates_path

app/views/event_dates/index.html.slim
h1 Listing event_dates

table
  tr
    th Start time
    th End time
    th Room
    th
    th
    th

  - @event_dates.each do |event_date|
    tr
      td= event_date.start_time
      td= event_date.end_time
      td= event_date.room
      td= link_to 'Show', event_date
      td= link_to 'Edit', edit_event_date_path(event_date)
      td= link_to 'Destroy', event_date, :confirm => 'Are you sure?', :method => :delete

br

= link_to 'New Event date', new_event_date_path

app/views/event_dates/new.html.slim
.container
  .content#event_date_page
    h1 New event_date

    == render 'form'

    = link_to 'Back', event_dates_path

app/views/event_dates/new_exam.html.slim
.container
  .content#event_date_page
    h1 Neuer Klausurtermin

    = simple_form_for @event_date do |f|
      -if @event_date.errors.any?
        #error_explanation
          h2 = "#{pluralize(@event_date.errors.count, "error")} prohibited this event_date from being saved:"
          ul
            - @event_date.errors.full_messages.each do |msg|
              li= msg
      
      = f.input :start_time, label: "Datum", as: :date, start_year: Date.today.year, end_year: Date.today.year+1, order: [:day, :month, :year], required: true
      = f.hidden_field :type

      = f.button :submit, "Speichern"
      br 
      br
      = link_to 'Back', event_dates_path