config/routes.rb
KITBox::Application.routes.draw do

  mount API => '/api'

  resources :dashboard, only: :index
  resources :documents, only: :new
  resources :search, only: :index
  resources :users, only: [:new]
  
  
  resources :timetable, only: :index do
    collection do
      get 'regenerate'
      get 'exam'
    end
  end
  match '/timetable/:timetable_id.ics', to: 'timetable#ical', :as => :timetable_ical


  resources :events, only: [:show] do
    member do
      get 'subscribe'
      get 'unsubscribe'
      get 'dates'
    end
    resources :dates, controller: "event_dates", only: [:new, :create]
  end
  

  resources :map, only: [:index, :show] do
    collection do
      get 'search'
      get 'list'
    end
  end
  

  resources :vvz, only: [:index, :show, :preload] do
    member do
      get "events/:event_id" => "vvz#events", :as => :event
      get "preload", format: "js"
    end
  end


  # skips login proccess
  if %w( development test cucumber ).include?(Rails.env.to_s)
    match "/backdoor" => "sessions#backdoor", :as => :backdoor
  end


  post "/signin" => "sessions#create", :as => :signin
  match "/signout" => "sessions#destroy", :as => :signout
  match "/signup" => "users#new", :as => :signup


  get '/robots.txt' => 'welcomes#robots'


  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  root :to => 'dashboard#index', :constraints => RoleConstraint.new(:user)
  root :to => redirect("/vvz")

  # See how all your routes lay out with "rake routes"
end

app/controllers/map_controller.rb
class MapController < ApplicationController

  caches_action :index, :show, :list, :layout => false
  caches_page :search

  def search
    result = Poi.search(params[:q]).map(&:to_search_json)
    render json: result.take(10)
  end

  def index
    colors = ["#4499ff", "#324189", "#730F5B", "#F52410", "#188D98", "#90B127", "#3165C9", "#2A9C6C", "#F67710"]
    @pois = Poi.all(:include => :poi_groups)
    @poi = Poi.find_by_id(params[:id])
    
    @js_pois = @pois.map do |poi| 
      data = poi.as_json.slice("id", "name", "lat", "lng", "building_no", "address")
      data["poi_group_ids"] = poi.poi_group_ids
      data
    end
    @groups_with_orphan = PoiGroup.all_with_orphan
    @colors = {}
    @groups_with_orphan.each {|group| @colors[group] = colors.pop }
    @groups = PoiGroup.all
  end

  def list
    @categories = PoiGroup.all
  end

  def show
    index
    render :index
  end

end

app/views/map/_form.html.slim
= form_for @poi, :url => map_path(@poi) do |f|
  -if @poi.errors.any?
    #error_explanation
      h2 = "#{pluralize(@poi.errors.count, "error")} prohibited this map_edit from being saved:"
      ul
        - @poi.errors.full_messages.each do |msg|
          li= msg

  .field
    = f.label :name, "Name"
    = f.text_field :name
  .field
    = f.label :building_no, "Gebäudenummer"
    = f.text_field :building_no
  .field
    = f.label :address, "Adresse"
    = f.text_field :address
  #map-area
    = render partial: "map"
    #pos_changed Die Position wurde verändert.
  .field
    = f.hidden_field :lat, id: "form_lat"
    = f.hidden_field :lng, id: "form_lng"

  .form-actions
      button.btn.btn-primary type="submit" Speichern
      |  
      button.btn Abbrechen

app/views/map/_map.html.slim
| <script src="https://maps.googleapis.com/maps/api/js?sensor=false"></script>
.poi_map data-lat=@poi.lat data-lng=@poi.lng data-editable="true"

app/views/map/edit.html.slim
.container.map
   .content
      h2 Ort bearbeiten
      nav 
         = link_to 'Show', map_path(@poi)
         '|
         = link_to 'Back', map_path 
      hr.clear

      == render 'form'

app/views/map/index.html.slim
- if @poi
  - page_title @poi.name
- else
  - page_title "Campus Karte"
== javascript_include_tag "map", defer: true
/
  <style>
    html, body, #map_canvas {
      /* margin: 0;
      padding: 0; */
      height: 100%;
    }
  </style>
| <script src="https://maps.googleapis.com/maps/api/js?sensor=false"></script>
.container#map-page.map
  .content
    header
      h1 KIT Campus Karte
      /input#map-search.input-medium.search-query type="search" placeholder="Suche nach Orten"
      .search-input
        input.typeahead id="map-search" type="search" value="" placeholder="Suche nach Orten" autocomplete="off"
      hr.clear
      /a.btn.edit 
        / rel="tooltip" title="Karte bearbeiten"
        i.icon-edit
        |  Karte Bearbeiten
      
    .no-padding
      #map_canvas data-poi=@poi.to_json.to_json
      
    br
    ul.flat#categories_selector.categories
      - @groups.each do |group|
        li
          label.btn.btn-label for="ccb#{group.id}" style="border-left-color:#{@colors[group]};"
            input id="ccb#{group.id}" type="checkbox" data-group-id=group.id data-pois=group.pois.map(&:id) data-color=@colors[group][1..6]
            = group.name

    br
    = link_to "Liste aller Einrichtungen", list_map_index_path

/
  #edit_modal.modal.hide.fade tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true"
    .modal-header
      button.close type="button" data-dismiss="modal" aria-hidden="true" 
        i.icon-remove
      h3#myModalLabel Karte bearbeiten
    .modal-body
      p Such dir einen Ort aus, den du bearbeiten möchtest:
      br
      .row
        input.input-medium.search-query type="search" placeholder="Suche"
        span.seperator
        select
          option value="" Auswahl
          - @groups_with_orphan.each do |group|
            optgroup label=group.name
              - group.pois.each do |poi|
                option value=poi.id = poi.name
      br
    .modal-footer
      .btn.pull-left#add-poi-btn
        i.icon-plus
        |  Ort hinzufügen
      a.btn data-dismiss="modal" Schließen
  

  #edit_modal2.modal.hide.fade tabindex="-2" role="dialog" aria-labelledby="myModalLabel2" aria-hidden="true"
    .modal-header
      button.close type="button" data-dismiss="modal" aria-hidden="true" 
        i.icon-remove
      h3#myModalLabel2 Karte bearbeiten
    .modal-body
      label Name
      input.span4 name="name" type="text"
      .map style="height: 200px;"
      label Kategorie
      ul.flat.categories
        - @groups.each do |group|
          li
            label.btn for="cb#{group.id}"
              /input id="cb#{group.id}" type="checkbox" data-id=group.id
              input id="cb#{group.id}" type="radio" name="categorie" value=group.id
              = group.name
    /  button.category_label title="entfernen"
        | Gebäude 
        i.icon-ok
        i.icon-remove
      button.category_label title="entfernen"
        | Essen 
        i.icon-ok
        i.icon-remove
        / icon-minus-sign
      button.category_label.add title="hinzufügen"
        | Parkplätze 
        i.icon-plus
    .modal-footer
      a.btn.btn-primary.save_btn data-dismiss="modal" Speichern
      a.btn data-dismiss="modal" Schließen

/ preload overlay
/ img src="/Campus-Sued.png" style="display: none;"

javascript:
  var pois = #{raw @js_pois.to_json};
  var poi = #{raw @poi ? @poi.to_json.to_json : "null"};

app/views/map/list.html.slim
- page_title "Liste aller Einrichtungen"
.container.map
  .content
    h1 Liste aller Einrichtungen
    hr.clear
    
    ul.nav.nav-tabs
      - @categories.each do |c|
        li
          a href="##{c.name}" = c.name
      
    ul.unstyled.big-list
      li
        - @categories.each do |c|
          h2 id=c.name = c.name
          ul.unstyled
            - c.pois.sort_by(&:name).each do |poi|
              li
                = link_to poi.name, map_path(poi)
      
    /table.table
      
        tr
          th colspan="3" = c.name
        - c.pois.each do |poi|
          tr
            td= 
            td= link_to 'Bearbeiten', edit_map_path(poi)
            td= link_to 'Löschen', map_path(poi), :confirm => 'Are you sure?', :method => :delete

app/views/map/new.html.slim
h1 New map_edit

== render 'form'

= link_to 'Back', map_edits_path

app/views/map/show.html.slim
- content_for :base_title, " - KIT Campusmap"
- content_for :title, @poi.name
p#notice = notice

.container.map
  .content
    h2 
      = @poi.name
      nav
        /= link_to 'Bearbeiten', edit_map_path(@poi)
        / '|
        = link_to 'Übersicht', map_index_path
    #map-area.no-padding
      = render partial: "map"
    .info
      p
        i.icon-home 
        | Gebäudenummer: 
        = @poi.building_no
      p
        i.icon-envelope
        = @poi.address
      br
      br
      / p= @poi.type
      / p= @poi.category